ui: tape
concurrency: 2
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: ie
    version: 10..latest
  - name: safari
    version: 7..latest
browserify:
  - transform: babelify
